### ISSUE TITLE
Add to poem's Openapi specification via SecurityScheme

### ISSUE THREAD

**Issue by skrcka** [DDtKey/protect-endpoints#114]
I have managed to implement JWT middleware based on existing example and it works but there is no mention of it in the generated openapi specification. Is it possible to add it?

There is existing solution in raw poem-openapi that seems to include it: https://docs.rs/poem-openapi/latest/poem_openapi/derive.SecurityScheme.html

**Comment by DDtKey** [comment]
You should manually add a security scheme, because this crate is auth-type agnostic.
See [this example](https://github.com/DDtKey/protect-endpoints/issues/86#issuecomment-2048033482) in another issue.

Please, correct me if I got you wrong.

**Comment by skrcka** [comment]
The example works. I am overthinking it same as Nahuel. The extra security arg feels a little redundant but if there is no way to do it without adding it then I will roll with it. Thank you
