### ISSUE TITLE
Any plans for supporting salvo?

### ISSUE THREAD

**Issue by shujaatak** [DDtKey/protect-endpoints#55]
Wondering if there are plans for supporting other frameworks specially [salvo](https://github.com/salvo-rs/salvo)?

**Comment by DDtKey** [comment]
Hi @shujaatak,
There are plans to cover a couple more frameworks.

I'll have to do some research on `salvo` before giving a final answer. But I'll be happy to add it to the list.

Thanks for the question!

**Comment by DDtKey** [comment]
Looks like it's technically not that hard to support `salvo`!

**Comment by DDtKey** [comment]
Support for `salvo` and `axum` is on the way, they will actively reuse code since they are both `tower` compatible.

**Comment by DDtKey** [comment]
Initial version of `axum` support is released (but will be changed a bit later).

`Salvo` is next, already in progress and will reuse core functionality, however requires a little bit more time because of the salvo specific.

**Comment by DDtKey** [comment]
Finally here we are 😅  
`salvo` is supported now
