### ISSUE TITLE
Customise token lookup location

### ISSUE THREAD

**Issue by bangbaew** [DDtKey/protect-endpoints#66]
The Gofiber JWT middleware provides flexibility in configuring the token lookup location, allowing adherence to OpenAPI specifications. The `TokenLookup` key supports options such as Cookie, Header, Path, and Query. The default setting is `"header:Authorization"`, mirroring the behavior of this crate. However, in my frontend website, where I store the access token in cookies, ensuring compliance with OpenAPI specs, to transmit the access token to the Authorization header, the cookie cannot be set as `HttpOnly`, compromising security. Therefore, I aim to maintain `HttpOnly` while employing this crate to extract the token by reading cookies with a custom key.

![image](https://github.com/DDtKey/protect-endpoints/assets/29559559/0a381b2b-da25-4749-ae7b-0f3bbebbd8ca)

**Comment by DDtKey** [comment]
Hi @bangbaew,
to be honest I don't understand the issue and desired behavior. 

Which library do you use? it doesn't look related to this repository. It's authorization extension for popular Rust web-frameworks

**Comment by bangbaew** [comment]
> Hi @bangbaew, to be honest I don't understand the issue and desired behavior.
> 
> Which library do you use? it doesn't look related to this repository. It's authorization extension for popular Rust web-frameworks

Sorry for not being clear, I use Actix Web and use the crate in this repository to implement oidc authorization, but it seems to look up Bearer token from `Authorization` header, the desired behavior is to have to option to change the lookup location to `Cookie` or `Path` or `Query`, is this possible?

**Comment by bangbaew** [comment]
> This logic actually relates to authentication, while `actix-web-grants` provides only `authorization` part.
> 
> Do you currently use [actix-web-httpauth](https://github.com/actix/actix-extras/tree/master/actix-web-httpauth)? (from [this example](https://github.com/DDtKey/protect-endpoints/blob/main/actix-web-grants/examples/jwt-httpauth/main.rs)) In that case it's should be supported there, to allow token lookup from different places (not only header).
> 
> Currently it works with headers - https://docs.rs/actix-web-httpauth/0.8.1/actix_web_httpauth/headers/authorization/trait.Scheme.html
> 
> Instead, I could recommend to write your own token-extractor and integrate it with `actix-web-grants`, something like this:
> 
> ```rust
> async fn extract(req: &mut ServiceRequest) -> Result<HashSet<String>, Error> {
>     // simplified example, better to create your own `BearerToken` type and implement `FromRequest`.
>     let token = req
>         .cookie("your-cookie-name")
>         .map(|cookie| cookie.value())
>         // otherwise check header
>         .or_else(|| req.headers().get(..).to_str());
>         // or check path
>         // or check query
>         
>    let claims = claims::decode_jwt(parse_bearer_token(token)?)?;  
>    Ok(claims.permissions)
> }
> 
>    // this part is from `actix-web-httpauth` in general
>    fn parse_bearer_token(value: &str) -> Result<String, ParseError> {
>         // "Bearer *" length
>         if value.len() < 8 {
>             return Err(ParseError::Invalid);
>         }
> 
>         let mut parts = value.splitn(2, ' ');
> 
>         match parts.next() {
>             Some("Bearer") => {}
>             _ => return Err(ParseError::MissingScheme),
>         }
> 
>         let token = parts.next().ok_or(ParseError::Invalid)?;
> 
>         Ok(Bearer {
>             token: token.to_string().into(),
>         })
>     }
> ```
> 
> This incomplete example of course, just to demonstrate. But in fact, you need to find a crate which supports extraction from different sources or implement your own solution (which should be pretty simple actually).
> 
> I think your own type `BearerToken` with custom implementation of `FromRequest` should cover your needs. Additionally you can ask `actix-web-httpauth` to support this case 🙂

I don't use actix-web-httpauth, I use actix-4-jwt-auth (https://github.com/spectare/actix-4-jwt-auth), because it support OpenID Connect, I've been working on it and started a pull request on that repository to parse token from cookies, then I wrap this repository function in a middleware to attach the permissions from the token. Thanks!
