### ISSUE TITLE
Adding authentication to OpenAPI definition using poem_openapi

### ISSUE THREAD

**Issue by Nahuel-M** [DDtKey/protect-endpoints#86]
With poem_openapi, the openapi definition of every endpoint is generated from the endpoint definition. The poem-grants crate integrates seamlessly with poem_openapi, but sadly, I'm unable to show the required authentication in the openapi.json. 

I did manage this with poem_openapi itself, but it's not nearly as ergonomic as poem-grants.
Is there any solution I'm missing? Or is this something that needs contribution?

**Comment by DDtKey** [comment]
`poem_grants` provides abilities to authorize the request processing, but  authentication logic is part of application logic.

I.e `poem_grants` knows nothing how you extract the credentials and which security schema is used (it uses custom `extractor` function and not aware of the logic)

Depending on your requirements, you may try to use [SecurityScheme](https://docs.rs/poem-openapi/latest/poem_openapi/derive.SecurityScheme.html) from `poem_openapi`. 
Or as an alternative add `request_header` attribute ([docs.rs](https://docs.rs/poem-openapi/latest/poem_openapi/attr.OpenApi.html)) to your api. It can be used if you expect credentials/token passed in header.

**Comment by Nahuel-M** [comment]
Alright, this sound like I need to read up a bit more. Thanks for your advice!

I was indeed trying to get something like SecurityScheme to work with poem_grants, but that might be a bit far fetched.

**Comment by EvilWatermelon** [comment]
Maybe [Utoipa](https://github.com/juhaku/utoipa) a good solution for you.

**Comment by DDtKey** [comment]
Hi @EvilWatermelon 

Is there new information that caused you to reopen the issue?

Security-schema and `openapi` representation isn't responsibility of `poem_grants` as we discussed.

**Comment by Nahuel-M** [comment]
Sorry, you're faster at picking these up than I am at formulating my comments :)
I've been trying a few different things and I'm wondering what your thoughts are.

First of all, why does `poem_grants` have support for `poem_openapi`? I've been trying to find a way to both extract a bearer token to use with `poem_grants` _and_  reflect this in the `openapi` spec with `poem_openapi`. Currently I'm falling short. I can indeed use a [SecurityScheme](https://docs.rs/poem-openapi/latest/poem_openapi/derive.SecurityScheme.html), but combining this scheme with `poem_grants` has not been successful.

I would like to fill the gap I'm currently seeing, but I agree with you that `poem_grants` might not be the right place. Would you say the current gap is better filled on the `poem_openapi` side? 

Thanks!

**Comment by DDtKey** [comment]
We support `poem-openapi` just because it's configured another way than classic `poem`. It uses structures and additional macros.

Could you provide a minimal reproducible example of your attempt to use `SecurityScheme` with `poem-grants`? What exactly didn't work?

It would really help to find a solution for your use-case

**Comment by Nahuel-M** [comment]
So as far as I can see, I have two options. The first one is not to use `poem_grants`:

```
#[oai(path = "/resource", method = "post")]
async fn create(
    &self,
    Json(resource): Json<CreateResourceRequest>,
    // SecurityScheme is derived for OauthPermissions. I added some helper functions to make requesting permissions easier
    auth: OauthPermissions, 
) -> Result<Json<Resource>> {
    auth.has_permission("resource:CREATE")?;

    self.resource_database.create(&resource)
        .await
        .map(json_response(StatusCode::CREATED))
        .map_err(internal_server_error)
}
```
This option will show up in my `openapi` definition, because I derived the exact security schema myself. The part I don't like: 
* I don't have the grants as an attribute above my function, which I find a very clean solution. 
* I've written custom code to do something `poem_grants` already does.

The second option:
```
#[protect("resource:POST")]
#[oai(path = "/resource", method = "post")]
async fn create(
    &self,
    Json(resource): Json<CreateResourceRequest>,
) -> Result<Json<Resource>> {
    self.resource_database.create(&resource)
        .await
        .map(json_response(StatusCode::CREATED))
        .map_err(internal_server_error)
}
```

I love it! It's much cleaner. However, because I cannot derive `SecurityScheme` for [AuthDetails](https://github.com/DDtKey/poem-grants/blob/95807cfe866a035b28b6e4bbfb6b9a467a7bf21a/poem-grants/src/permissions/mod.rs#L26), this does not show up in my OpenApi definition.

I could of cource combine the two, but this would both cause an overhead in performance and readability, as the token would be parsed in two places.

I hope this makes my question clearer. If not, please let me know!

**Comment by DDtKey** [comment]
Did you try something like that:

```rs
#[derive(SecurityScheme)]
#[oai(ty = "bearer")]
struct MySecurityScheme(Bearer);

#[protect("resource:CREATE")]
#[oai(path = "/resource", method = "post")]
async fn create(
    &self,
    Json(resource): Json<CreateResourceRequest>,
    _security: MySecurityScheme,
) -> Result<Json<Resource>> {
    self.resource_database.create(&resource)
        .await
        .map(json_response(StatusCode::CREATED))
        .map_err(internal_server_error)
}
```

**Comment by Nahuel-M** [comment]
Sure, this works. I was looking for a solution that doesn't bring along a cost in performance and readability, but I might be overthinking this. 

Thanks for thinking along!
